# Generated by Django 3.2.25 on 2025-02-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("_users", "0001_initial"),
        ("_restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.BinaryField(blank=True, null=True)),
                ("karma", models.IntegerField(default=0)),
                ("flagged", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="_users.customer",
                    ),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="_users.moderator",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="_restaurants.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reply", models.BinaryField(blank=True, null=True)),
                ("karma", models.IntegerField(default=0)),
                ("flagged", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="_restaurants.comment",
                    ),
                ),
                (
                    "commenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="_users.customer",
                    ),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="_users.moderator",
                    ),
                ),
            ],
        ),
    ]
