# Generated by Django 4.2.20 on 2025-03-14 16:37

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0002_comment_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="geo_coords",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326
            ),
        ),
    ]
