# Generated by Django 4.2.20 on 2025-04-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0004_restaurant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
