# Generated by Django 4.2.20 on 2025-04-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0005_restaurant_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="health_rating",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="comment",
            name="title",
            field=models.CharField(default="title", max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
