# Generated by Django 4.2.20 on 2025-04-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0005_restaurant_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="is_activated",
            field=models.BooleanField(default=True),
        ),
    ]
