# Generated by Django 4.2.20 on 2025-04-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "_restaurants",
            "0006_comment_health_rating_comment_rating_comment_title_and_more",
        ),
        ("_restaurants", "0007_alter_restaurant_is_activated"),
    ]

    operations = []
