# Generated by Django 4.2.20 on 2025-04-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0008_merge_20250409_2156"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="deactivation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
