# Generated by Django 4.2.20 on 2025-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0010_remove_restaurant_deactivation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="deactivation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="is_activated",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="RestaurantDeactivated",
        ),
    ]
