# Generated by Django 4.2.20 on 2025-04-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0012_remove_comment_flagged_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="deactivated_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
