# Generated by Django 4.2.20 on 2025-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0015_customer_karmatotal"),
        ("_restaurants", "0014_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="k_voters",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="voted_comments",
                to="_users.customer",
            ),
        ),
    ]
