# Generated by Django 4.2.20 on 2025-04-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0016_alter_customer_karmatotal"),
        ("_restaurants", "0015_comment_k_voters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="k_voters",
            field=models.ManyToManyField(
                blank=True, related_name="voted_comments", to="_users.customer"
            ),
        ),
    ]
