# Generated by Django 3.2.25 on 2025-02-28 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("_restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Moderator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="DM",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.BinaryField()),
                ("flagged", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="_users.moderator",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_dms",
                        to="_users.customer",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_dms",
                        to="_users.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="_users.customer",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="_restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "restaurant")},
            },
        ),
        migrations.AddConstraint(
            model_name="dm",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("sender", django.db.models.expressions.F("receiver")),
                    _negated=True,
                ),
                name="chk_dm_sender_receiver",
            ),
        ),
    ]
