# Generated by Django 4.2.20 on 2025-03-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(
                default="<django.db.models.fields.EmailField>", max_length=255
            ),
        ),
    ]
