# Generated by Django 4.2.20 on 2025-04-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0002_customer_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
