# Generated by Django 4.2.20 on 2025-04-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0003_alter_customer_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="dm",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
