# Generated by Django 4.2.20 on 2025-04-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0004_dm_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="fav_cuisine",
            field=models.CharField(default="", max_length=255),
        ),
    ]
