# Generated by Django 4.2.20 on 2025-04-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0004_dm_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_activated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="moderator",
            name="username",
            field=models.CharField(default="TestAdmin", max_length=255),
            preserve_default=False,
        ),
    ]
