# Generated by Django 4.2.20 on 2025-04-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0005_customer_fav_cuisine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="fav_cuisine",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
