# Generated by Django 4.2.20 on 2025-04-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0005_customer_is_activated_moderator_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_activated",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
