# Generated by Django 4.2.20 on 2025-04-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0006_alter_customer_fav_cuisine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="fav_cuisine",
        ),
    ]
