# Generated by Django 4.2.20 on 2025-04-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0006_alter_customer_is_activated_and_more"),
        ("_users", "0007_remove_customer_fav_cuisine"),
    ]

    operations = []
