# Generated by Django 4.2.20 on 2025-04-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0009_customer_deactivation_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDeactivated",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=255)),
                (
                    "is_activated",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("deactivation_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="deactivation_reason",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_activated",
        ),
    ]
