# Generated by Django 4.2.20 on 2025-04-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0013_remove_dm_flagged_by_dm_flagged_by_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deactivated_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
