# Generated by Django 4.2.20 on 2025-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0014_customer_deactivated_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="karmatotal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
