# Generated by Django 4.2.20 on 2025-04-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0015_customer_karmatotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="karmatotal",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
