# Generated by Django 4.2.20 on 2025-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0015_customer_blocked_customers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="blocked_customers",
            field=models.ManyToManyField(blank=True, to="_users.customer"),
        ),
    ]
