# Generated by Django 4.2.20 on 2025-04-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0016_alter_customer_blocked_customers"),
        ("_users", "0016_alter_customer_karmatotal"),
    ]

    operations = []
